"""
GUI レイアウト・見た目の定数（ウィンドウ幅、履歴ドロップダウン、接続カード等）。
"""

# 幅は固定。縦は起動時に状態A/Bの要請高さの max を `_fixed_window_height` に保存し、切替時も `_fit_window_height_to_content` で同じ高さを維持する
WINDOW_WIDTH = 400
WINDOW_GEOMETRY_BOOTSTRAP = f"{WINDOW_WIDTH}x420"

# 検知ランプ（Room=arenahere テンプレ一致、ID=5桁部屋IDを読取）
LAMP_ROOM_ON = "#1EBFE5"
LAMP_ROOM_OFF = "#2A4F58"
LAMP_ID_ON = "#12FF88"
LAMP_ID_OFF = "#2A4035"

# 履歴ドロップダウン（対象ソースのコンボボックスと揃える見た目トークン）
HISTORY_CORNER_RADIUS = 6
HISTORY_TRIGGER_HEIGHT = 28
HISTORY_TEXT_PAD_LEFT = 8
HISTORY_TEXT_PAD_RIGHT = 6
HISTORY_GAP_TEXT_TO_CARET = 4
HISTORY_CARET_CANVAS_W = 12
HISTORY_MIN_TRIGGER_WIDTH = 68
HISTORY_MENU_INNER_PAD = 3
HISTORY_ITEM_HEIGHT = 20
HISTORY_FG = "#333333"
HISTORY_TRIGGER_TEXT = "#9a9a9a"
HISTORY_BORDER = "#555555"
HISTORY_HOVER = "#444444"
HISTORY_WINDOW_EDGE_RIGHT = 12
HISTORY_WINDOW_EDGE_LEFT = 8

ID_SIDE_RESERVE_FOR_LAMPS = 88
LAMP_LABEL_HIT_WIDTH = 52

CONNECTION_CARD_CORNER_RADIUS = 8
CONNECTION_HEADER_ROW_HEIGHT = 32
CONNECTION_CARD_UNIFORM_PAD = 2
CONNECTION_HEADER_PADY = CONNECTION_CARD_UNIFORM_PAD
CONNECTION_CARD_INSET = CONNECTION_CARD_UNIFORM_PAD
CONNECTION_BODY_PACK_PAD_BOTTOM = CONNECTION_CARD_UNIFORM_PAD
CONNECTION_ROW_PADY = 1
CONNECTION_BTN_CONNECT_PADY = (4, CONNECTION_CARD_UNIFORM_PAD)
CONNECTION_COMBO_PADY = (0, CONNECTION_CARD_UNIFORM_PAD + 2)
CONNECTION_CARD_PEER_GAP = 5
RUN_MIDDLE_GRID_PADY = (4, 1)
RUN_SPACER_WEIGHT_TOP = 8
RUN_SPACER_WEIGHT_BOTTOM = 3
RUN_CLUSTER_BTN_STATUS_GAP = 6
CONNECTION_CARET_W = 14
CONNECTION_CARET_H = 12
CONNECTION_CARET_COLOR = "#b0b0b0"
HEADER_CARET_PAD_X = 8

FRAME_ID_OUTER_HEIGHT = 100

BOTTOM_SEPARATOR_PADX = 28
BOTTOM_SEPARATOR_PADY_TOP = 5
BOTTOM_SEPARATOR_PADY_BOTTOM = 3
BOTTOM_SEPARATOR_HEIGHT = 2

# 起動時自動接続（`_auto_start_sequence`）: 接続完了を待ってから監視開始
AUTO_START_INITIAL_DELAY_MS = 1000
AUTO_START_RETRY_INTERVAL_MS = 500
AUTO_START_MAX_ATTEMPTS = 60  # 約 30 秒 + 初期待機

# `OCRWorker` 停止時の `Thread.join` 上限（`_stop_worker` / 終了処理）
WORKER_JOIN_TIMEOUT_SEC = 3.0
